<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Catalog.Domain\Catalog.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
  </ItemGroup>

</Project>
